Slightly unjank pistachio-manager (its a mess still)
Signed-off-by: Pistasjis <odyssey346@disroot.org>

diff --git a/pistachio-manager b/pistachio-manager
--- a/pistachio-manager
+++ b/pistachio-manager
@@ -2,7 +2,7 @@
 
 # Pistachio Linux's Distrobox management script
 # Licensed under GPLv3
-VERSION="1.0.0"
+VERSION="1.0.1"
 
 # help functions for pistachio-manager
 
@@ -63,69 +63,86 @@ ShowCreateTerminalProfileHelp()
     echo "container - The name of the container to create a profile for."
 }
 
+# checks for dependencies
+DependencyCheck() 
+{
+    if ! command -v distrobox &> /dev/null; then
+        echo "distrobox is not installed. Please report this issue on GitHub."
+    fi
+    if ! command -v podman &> /dev/null; then
+        echo "podman is not installed. Please report this issue on GitHub."
+    fi
+}
+
 CreateContainer() 
 {
-        param=$1
-        if ! command -v distrobox &> /dev/null; then
-            echo "distrobox is not installed. Please report this issue on GitHub."
-        fi
-        if ! command -v podman &> /dev/null; then
-            echo "podman is not installed. Please report this issue on GitHub."
-        fi
+    param=$1
+    DependencyCheck
 
-        if [ $param = "arch" ]
+    if [ $param = "arch" ]
+    then
+        if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
         then
-            if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
-            then
-                echo "Creating container $param..."
-                distrobox create $param --image archlinux:latest
-                echo "Container $param created."
-            else
-                echo "Container $param already exists."
-            fi
+            echo "Creating container $param..."
+            distrobox create $param --image archlinux:latest
+            echo "Container $param created."
+        else
+            echo "Container $param already exists."
         fi
+    fi
 
-        if [ $param = "debian" ]
+    if [ $param = "debian" ]
+    then
+        if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
         then
-            if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
-            then
-                echo "Creating container $param..."
-                distrobox create debian --image debian:stable
-                echo "Container $param created."
-            else
-                echo "Container $param already exists."
-            fi
+            echo "Creating container $param..."
+            distrobox create debian --image debian:stable
+            echo "Container $param created."
+        else
+            echo "Container $param already exists."
         fi
+    fi
 
-        if [ $param = "fedora" ]
+    if [ $param = "fedora" ]
+    then
+        if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
         then
-            if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
-            then
-                echo "Creating container $param..."
-                distrobox create $param --image fedora:latest
-                echo "Container $param created."
-            else
-                echo "Container $param already exists."
-            fi
+            echo "Creating container $param..."
+            distrobox create $param --image fedora:latest
+            echo "Container $param created."
+        else
+            echo "Container $param already exists."
         fi
+    fi
 
-        if [ $param = "pistachiolinux" -o $param = "pistachio-linux" ]
-        then
-            echo "You cannot create a container for Pistachio Linux."
-            exit 1
-        fi
+    if [ $param = "pistachiolinux" -o $param = "pistachio-linux" ]
+    then
+        echo "You cannot create a container for Pistachio Linux."
+        exit 1
+    fi
 
-        if [ $param != "arch" -a $param != "debian" -a $param != "fedora" -a $param != "pistachiolinux" -a $param != "pistachio-linux" ]
-        then
-            echo "Invalid distro. Valid options are \"arch\", \"debian\" and \"fedora\"."
-            exit 1
-        fi
+    if [ $param != "arch" -a $param != "debian" -a $param != "fedora" -a $param != "pistachiolinux" -a $param != "pistachio-linux" ]
+    then
+        echo "Invalid distro. Valid options are \"arch\", \"debian\" and \"fedora\"."
+        exit 1
+    fi
+}
+
+CheckContainerExists()
+{
+    param=$1
+    if [ $(podman ps -a | grep $param | wc -l) -eq 0 ]
+    then
+        echo "Container $param does not exist."
+        exit 1
+    fi
 }
 
 CreateTerminalProfile()
 {
     param=$1
     echo "Creating terminal profile for $param..."
+    CheckContainerExists $param
     echo -e "What's your Windows username?: \c" 
     read username
     profileTemplate='{"profiles": [ { "name": "'$1' (on Pistachio)", "commandline": "wsl.exe -d PistachioLinux distrobox enter '$1'", "colorScheme": "Campbell", "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png" }]}'
@@ -169,12 +186,7 @@ then
     fi
     if [ $# -eq 3 ]
     then
-        if ! command -v distrobox &> /dev/null; then
-            echo "distrobox is not installed. Please report this issue on GitHub."
-        fi
-        if ! command -v podman &> /dev/null; then
-            echo "podman is not installed. Please report this issue on GitHub."
-        fi
+        DependencyCheck
         if [ $2 = "pistachiolinux" || $2 = "pistachio-linux" ]
         then
             echo "If you want to install a package in Pistachio Linux, run \"sudo apt install $3\"."
@@ -327,6 +339,22 @@ then
         if [ $2 = "enter" ]
         then
             ShowEnterHelp
+        fi
+        if [ $2 = "remove" ]
+        then
+            ShowRemoveHelp
+        fi
+        if [ $2 = "uninstall" ]
+        then
+            ShowUninstallHelp
+        fi
+        if [ $2 = "version" ]
+        then
+            ShowVersionHelp
+        fi
+        if [ $2 = "create-terminal-profile" ]
+        then
+            ShowCreateTerminalProfileHelp
         fi
     fi
 fi
